CREATE SCHEMA encuestas;

CREATE TABLE encuestas.estudiantil (
	id	serial	primary key,
	id_curso	int4	not null	references cursos,
	id_alumno	int4	not null	references alumnos,
	p1	int2	not null,
	p2	int2	not null,
	p3	int2	not null,
	p4	int2	not null,
	p5	int2	not null,
	p6	int2	not null,
	p7	int2	not null,
	p8	int2	not null,
	p9	int2	not null,
	p10	int2	not null,
	p11	int2	not null,
	p12	int2	not null,
	p13	int2	not null,
	p14	int2	not null,
	p15	int2	not null,
	p16	int2	not null,
	p17	int2	not null,
	p18	int2	not null,
	p19	int2	not null,
	p20	int2	not null,
	p21	int2	not null,
	p22	int2	not null,
	p23	int2	not null,
	p24	int2	not null,
	p25	int2	not null,
	fecha	timestamp	default now(),
	UNIQUE(id_curso,id_alumno)
);
