<?php

if (empty($tipo_contrato)) { $tipo_contrato = "Anual"; }

$titulo = "<table width='100%'>"
        . "  <tr>"
        . "    <td align='left'><img src='img/logo_umc_apaisado.jpg'></td>"
        . "    <td align='right'>Nº $id_contrato</td>"
        . "  </tr>"
        . "</table>"
        . "<b>CONTRATO DE PRESTACIÓN DE SERVICIOS EDUCACIONALES</b><br>";

$TEXTO = "Entre la Universidad Miguel de Cervantes, Corporación de Derecho Privado de Educación Superior, "
       . "Rut: 73.124.400-6, representada por su $REPRESENTANTE_LEGAL, ambos domiciliados "
       . "calle Mac Iver N° 370, de esta ciudad, en adelante «la Universidad» y/o «UMC», por una parte, y "
       . "por la otra, don(ña) $nombre_al, de nacionalidad $nacionalidad_al, domicilio en $domicilio_al, en adelante "
       . "«el alumno», y don(ña) $nombre_rf, de nacionalidad $nacionalidad_rf, profesión $profesion_rf, "
       . "estado civil $est_civil_rf, rut $rut_rf, domicilio en $domicilio_rf, en adelante "
       . "«el apoderado», en conformidad a las disposiciones legales y al Código Civil se ha convenido el "
       . "siguiente contrato de prestación de servicios educacionales:<br><br>"
       . "<b>PRIMERO</b><br>"
       . "Por el presente acto el (compareciente don $nombre_al) se matricula como alumno regular de la Universidad Miguel "
       . "de Cervantes, en el programa de $carrera_al.<br><br>"
       . "<b>SEGUNDO</b><br>"
       . "En virtud del presente contrato, la Universidad se obliga a mantener el cupo correspondiente, para "
       . "el alumno regular en los servicios docentes que le sean pertinentes y que prestará durante los periodos "
       . "académicos en que se matricula. Para estos efectos, se considerará como parte integrante de este contrato "
       . "el plan de estudios de la carrera en la que se matricula el alumno. Esto, sin perjuicio del derecho de la "
       . "UMC de modificar ese plan de estudios en atención a razones académicas, exigencias o recomendaciones de la "
       . "autoridad pública competente y/o de los organismos responsables de realizar los procesos de acreditación "
       . "institucional y/o de carreras. Por su parte el alumno y su apoderado declaran conocer el Estatuto y todos los "
       . "reglamentos de la Universidad que regulan las actividades académicas y formativas para obtener el respectivo "
       . "título y/o grado, y los derechos y obligaciones del alumno. Además se deja constancia que la Información "
       . "pertinente, Estatutos y Reglamentos aplicables a este contrato están publicados en el portal «www.umcervantes.cl» "
       . "hecho del cual el estudiante y su apoderado certifican conocer. El alumno en este acto se obliga a conocer y a "
       . "respetar la reglamentación interna de la Universidad, y en general toda otra norma que emane de la "
       . "institucionalidad universitaria. El incumplimiento por parte del alumno de dicha reglamentación dará derecho a "
       . "la UMC a poner término al presente contrato, sin necesidad de declaración judicial.<br><br>"
       . "Las actividades académicas correspondientes al programa en el que se matriculó el alumno tendrán lugar en la "
       . "sede central de la Universidad, o en otra instalación según lo disponga la UMC. El alumno y su apoderado "
       . "declaran conocer la infraestructura de la universidad  y manifiestan su plena satisfacción con esta.<br><br>"
       . "<b>TERCERO</b><br>"
       . "Los cursos y/o asignaturas que la Universidad imparte corresponden, al plan de estudios de la respectiva "
       . "carrera. Cada uno de estos cursos se impartirá sólo una vez al año, en el semestre académico "
       . "correspondiente, determinado por  el plan de estudios de la carrera en la que se matriculó el alumno. "
       . "Aquel alumno que haya realizado retiro, suspensión de estudios o abandono y posteriormente decida "
       . "solicitar formalmente su reincorporación deberá adscribirse al  plan de estudios vigente en su carrera.<br><br>"
       . "La Universidad podrá impartir cursos y/o asignaturas de carácter transversal, del mismo plan de estudios "
       . "o que tengan el mismo programa, esto es, cursos y/o asignaturas en los que participen alumnos de cualquier "
       . "carrera y/o jornada, y estos se podrán impartir en la jornada vespertina y el día Sábado. De igual modo, "
       . "aquellas asignaturas de la jornada diurna que no reúnan un mínimo de diez estudiantes regulares "
       . "válidamente inscritos para el respectivo período y nivel, podrán ser fusionadas con las asignaturas "
       . "iguales de la jornada vespertina, abriendo para ello un solo curso en horario vespertino y del día "
       . "sábado.<br><br>"
       . "Los cursos y/o asignaturas que el alumno podrá inscribir en cada semestre dependerán del cumplimiento "
       . "de los pre-requisitos académicos y de admisión establecidos en el plan de estudios de la respectiva "
       . "carrera, según la jornada en que se matriculó y en conformidad con la reglamentación vigente en la "
       . "Universidad.<br><br>"
       . "A los alumnos que no inscriban la carga curricular correspondiente a su Plan de Estudios o no efectúen la "
       . "inscripción de asignaturas en tiempo, oportunidad y forma establecida por la UMC, no se les hará devolución "
       . "arancelaria alguna, debiendo dar cumplimiento a la totalidad de la obligación contraída. No forma parte de "
       . "este contrato la entrega de textos, material de estudio o de trabajos necesarios para el cumplimiento de "
       . "las exigencias académicas del alumno.<br><br>"
       . "<b>CUARTO</b><br>"
       . "Si no se completare un número mínimo de 45 alumnos en primer nivel del programa, y que el alumno y su "
       . "apoderado declaran conocer, la UMC podrá optar por no abrir dicho programa. Dada esta situación, "
       . "la Universidad podrá ofrecer otras alternativas al alumno o, si éste lo solicita, se procederá a dejar "
       . "sin efecto el contrato firmado, reintegrando los eventuales pagos efectuados y la documentación "
       . "entregada por el alumno y recibida por la UMC.<br><br>"
       . "Asimismo, los horarios y jornadas de los cursos serán determinados semestralmente por la Dirección de la Escuela respectiva en "
       . "función de las necesidades de la estructura curricular. En todo caso, los cursos y/o asignaturas podrán "
       . "dictarse de lunes a sábado cualquiera sea la jornada que curse el alumno.<br><br>"
       . "<b>QUINTO</b><br>"
       . "El valor del derecho de matrícula y el valor del arancel anual corresponden al total de la prestación "
       . "contratada para dicho período. La Universidad fijará anualmente estos derechos y el valor de la "
       . "colegiatura.<br><br>"
       . "Se deja establecido que aún cuando el alumno, por cualquier causa o motivo, no hiciere uso de este "
       . "servicio educacional deberá dar cumplimiento a la totalidad de la obligación contraída en este contrato "
       . "y en los pagarés que sustentan dicha obligación.<br><br>"
       . "Los pagos mensuales, cuando corresponda, se efectuarán en las oficinas de la Universidad o mediante "
       . "transferencia electrónica debidamente informada a la UMC o por medio de la Institución financiera a "
       . "la cual ella hubiere encomendado su recaudación y/o cobro, no estando obligadas ni la Universidad ni "
       . "la Institución financiera a notificar en cada oportunidad las fechas de vencimiento del compromiso "
       . "del pago.<br><br>"
       . "En el caso de pago en cuotas, el incumplimiento o mora en el pago de alguna de ellas, dará derecho a la "
       . "Universidad a exigir el pago total de lo adeudado.<br><br>"
       . "El alumno y su apoderado manifiestan su conformidad en que a partir de esta fecha, toda información y "
       . "comunicación oficial de la Universidad sea enviada a través del correo electrónico, a la dirección "
       . "personal que para estos efectos se ha creado a cada alumno. Su dirección de e-mail es la correspondiente "
       . "al primer nombre seguido de un punto y seguido de su apellido paterno más la expresión «@al.umcervantes.cl». "
       . "En caso de existir una dirección electrónica identica anteriormente asignada a un alumno antiguo de la UMC, "
       . "el Departamento de Informática asignará una dirección electrónica distinta para el alumno, según establecen "
       . "los procedimientos respectivos. Sin perjuicio de lo anterior, la Universidad podrá enviar comunicaciones al "
       . "domicilio que el alumno haya entregado a la Universidad. En todo caso será responsabilidad del alumno "
       . "informar del cambio de domicilio.<br><br>"
       . "<b>SEXTO</b><br>"
       . "En el caso de alumnos nuevos, esto es, aquellos que ingresan por primera vez a la Universidad, la "
       . "UMC podrá poner término al presente contrato, si este no hubiere cumplido con los "
       . "requisitos de admisión e ingreso. En este caso, junto a la rescisión del presente contrato, la Universidad "
       . "devolverá los pagos efectuados por el alumno por los servicios inicialmente convenidos, así como la "
       . "documentación entregada por el alumno y recibida por la UMC.<br><br>"
       . "El alumno y su apoderado, en este acto expresan su consentimiento y conformidad con la facultad de la "
       . "Universidad de extender o denegar certificaciones académicas o de cualquier otro orden, ante el incumplimiento "
       . "de las obligaciones contraídas en virtud del presente contrato, renunciando desde ya al ejercicio de acciones "
       . "legales de cualquier naturaleza por este motivo. Los alumnos que a través de este documento hayan reprogramado "
       . "deuda anterior quedarán sujetos a igual restricción y renuncia de acciones.<br><br>"
       . "<!-- PAGE BREAK -->"
       . "El alumno deberá observar las normas reglamentarias internas para inscribir sus cursos o actividades; por "
       . "consiguiente, si el estudiante debe repetir uno o más cursos alterándose el orden o número de cursos que debe "
       . "inscribir, ello será de su exclusiva responsabilidad, es decir, la Universidad no estará obligada a otorgar "
       . "facilidades, horarios especiales u otras medidas equivalentes.<br><br>"
       . "También se deja constancia que el proceso de graduación constituye una actividad académica regular del "
       . "programa, por lo tanto requiere que el estudiante esté matriculado para el período académico "
       . "respectivo, y que cancele los aranceles correspondientes a su proceso de graduación.<br><br>"
       . "<b>SÉPTIMO</b><br>"
       . "De todas las obligaciones económicas y financieras estipuladas en el presente contrato o que se deriven "
       . "de él, serán solidaria e indivisiblemente responsables, el estudiante y su apoderado. Por este instrumento, "
       . "el alumno y su apoderado autorizan expresamente y en conformidad a la Ley, a la Universidad Miguel de Cervantes "
       . "para que, separada e individualmente, en caso de simple retardo, mora o incumplimiento total o parcial de las "
       . "obligaciones contraídas en este contrato, sus datos personales y los demás derivadas de éste (del alumno y/o su "
       . "apoderado) puedan ser tratados y/o comunicados a terceros sin restricciones en la base de datos del Boletín "
       . "Electrónico Dicom de Equifax o en sistema de información comercial creado para estos efectos y que la UMC "
       . "decida utilizar.<br><br>"
       . "<b>OCTAVO</b><br>"
       . "En el caso que el alumno presente formalmente su solicitud de retiro, suspensión de estudios o que haya "
       . "sido eliminado por rendimiento académico o por sanción disciplinaria, en conformidad a  la reglamentación "
       . "vigente de la UMC, deberá pagar la totalidad de la deuda contraída en el presente contrato. Los plazos "
       . "para presentar solicitud de retiro o de suspensión de estudios estarán establecidos en el calendario "
       . "académico definido por la Vicerrectoría Académica y comunicado a través del sitio Web institucional.<br><br>"
       . "El alumno deberá estar al día en todas sus obligaciones económicas con la Universidad para poder incorporarse "
       . "a las actividades académicas del primer semestre del primer año, tener derecho a matricularse e inscribir "
       . "asignaturas en los períodos académicos sucesivos, a obtener certificaciones, hacer uso en plenitud de la "
       . "biblioteca y laboratorios de la Universidad y a presentarse y rendir evaluaciones solemnes y/o exámenes. "
       . "Si no lo estuviere, quedará suspendido de todos sus derechos académicos, económicos y administrativos "
       . "mientras persista la mora. Las fechas de evaluaciones solemnes y/o de exámenes no rendidos por esa causa "
       . "no serán recuperables debiendo, una vez solucionada su mora o protesto, esperar la próxima fecha regular "
       . "de evaluación o exámenes para su rendición.<br><br>"
       . "Así mismo los beneficios de becas, créditos o cualquier otro que le haya otorgado la Universidad con recursos "
       . "propios a un alumno, quedarán de inmediato sin efecto, si este cae en mora por falta de pago de sus obligaciones "
       . "pactadas con la Universidad.<br><br>"
       . "<b>NOVENO</b><br>"
       . "En caso que el estudiante ocasionare daños materiales al patrimonio de la Universidad, él y su apoderado "
       . "deberán pagar solidariamente la reparación o reposición de los daños causados, sin perjuicio de las sanciones "
       . "reglamentarias y/o legales que correspondan.<br>"
       . "Las partes dejan constancia que la Universidad no será responsable por los perjuicios producidos por la pérdida "
       . "o sustracción de efectos personales de propiedad del estudiante que se introduzcan o mantengan en los recintos "
       . "universitarios; por consiguiente, el estudiante declara conocer su obligación de mantener el debido resguardo "
       . "sobre dichos objetos.<br><br>"
       . "<!-- PAGE BREAK -->"
       . "<b>DÉCIMO</b><br>"
       . "La individualización del alumno y apoderado de la comparecencia y los datos de los servicios académicos "
       . "contratados son:<br><br>"
       . "<table cellpadding='2' cellspacing='0' border='1' align='center' width='90%'>"
       . "  <tr><td width='20%'>Alumna/alumno</td> <td width='80%'>$nombre_al</td></tr>"
       . "  <tr><td width='20%'>RUT Alumna/o</td>  <td width='80%'>$rut_al</td></tr>"
       . "  <tr><td width='20%'>Domicilio</td>     <td width='80%'>$domicilio_al</td></tr>"
       . "  <tr><td width='20%'>Fono Fijo</td>     <td width='80%'>$telefono_al</td></tr>"
       . "  <tr><td width='20%'>Fono Celular</td>  <td width='80%'>$tel_movil_al</td></tr>"
       . "</table><br>"
       . "<table cellpadding='2' cellspacing='0' border='1' align='center' width='90%'>"
       . "  <tr><td width='20%'>Carrera</td> <td width='80%'>$carrera_al</td></tr>"
       . "  <tr><td width='20%'>Jornada</td> <td width='80%'>$jornada_al</td></tr>"
       . "</table><br>"
       . "<table cellpadding='2' cellspacing='0' border='1' align='center' width='90%'>"
       . "  <tr><td width='20%'>Apoderado</td>     <td width='80%'>$nombre_rf</td></tr>"
       . "  <tr><td width='20%'>RUT Apoderado</td> <td width='80%'>$rut_rf</td></tr>"
       . "  <tr><td width='20%'>Domicilio</td>     <td width='80%'>$domicilio_rf</td></tr>"
       . "  <tr><td width='20%'>Fono Fijo</td>     <td width='80%'>$telefono_rf</td></tr>"
       . "  <tr><td width='20%'>Fono Celular</td>  <td width='80%'>$tel_movil_rf</td></tr>"
       . "</table><br>"
       . "El Derecho de Matrícula $tipo_contrato convenido es de \$ $monto_matricula ($monto_matricula_palabras pesos), que "
       . "se paga al contado, en este acto. "
       . $descuento_matricula
       . "El Derecho de Matrícula $tipo_contrato al que se hace mención en esta cláusula, bajo ninguna circunstancia estará "
       . "sujeto  a devolución.<br><br>"
       . "El Derecho de Colegiatura $tipo_contrato convenido es de \$ $monto_arancel ($monto_arancel_palabras pesos) que se "
       . "paga de la siguiente forma:"
       . "<table cellpadding='2' align='center'>"
       . "  <tr>"
       . "    <td nowrap>&raquo; Con el otorgamiento de una beca de Procedencia por la suma de</td>"
       . "    <td align='right'>\$ $monto_convenio</td>"
       . "  </tr>"
       . "  <tr>"
       . "    <td nowrap>&raquo; Con el otorgamiento de una beca de excelencia por la suma de</td>"
       . "    <td align='right'>\$ $monto_beca_arancel_excelencia</td>"
       . "  </tr>"
       . "  <tr>"
       . "    <td nowrap>&raquo; Con el otorgamiento de la beca UMC por la suma de</td>"
       . "    <td align='right'>\$ $monto_beca_arancel_umc</td>"
       . "  </tr>"
       . "  <tr>"
       . "    <td nowrap>&raquo; Al contado, en este acto, la suma de</td>"
       . "    <td align='right'>\$ $arancel_efectivo</td>"
       . "  </tr>"
       . "  <tr>"
       . "    <td nowrap>&raquo; Crédito interno UMC</td>"
       . "    <td align='right'>\$ $arancel_cred_interno</td>"
       . "  </tr>"
       . "  <tr>"
       . "    <td align='right'>Saldo</td>"
       . "    <td align='right'>\$ $arancel_saldo</td>"
       . "  </tr>"
       . "</table><br>"       
       . $tabla_pagare_cheques
       . "<!-- PAGE BREAK -->"
       . "<b>UNDÉCIMO</b><br>"
       . "Las partes dejan constancia de los siguiente:<br>"
       . "Que el incumplimiento o mora en el pago del servicio que por este acto se suscribe, facultará a la "
       . "Universidad para suspender al alumno el servicio educacional; y de persistir la morosidad, para poner "
       . "término a la calidad de alumno regular del estudiante. El simple retardo o mora en el pago de alguna de "
       . "las cuotas dará derecho a la UMC para exigir el pago del total de la deuda como si fuere de plazo vencido. "
       . "La mora o atraso en el pago generará un interés mensual que no superará la tasa máxima convencional. Asimismo, "
       . "la UMC podrá también, exigir el pago, por vía judicial o extrajudicial, de las sumas devengadas e impagas, "
       . "correspondientes al arancel pactado y/o externalizar la cobranza de la deuda en mora. El deudor moroso será "
       . "responsable de los gastos de protesto, cobranza extrajudicial y judicial y demás que genere su incumplimiento.<br><br>"
       . "Que en base a lo establecido en la Ley de Protección de los derechos de los Consumidores y en la normativa de "
       . "la Superintendencia de Bancos e Instituciones Financieras, existen recargos por concepto de cobranza "
       . "extrajudicial de los créditos o cuotas impagas detallados en la cláusula anterior, incluyendo honorarios "
       . "a cargo del deudor según los plazos que se indican mas adelante, los cuales serán cobrados directamente por "
       . "la UMC o por la empresa «Servicios de Control de Crédito S.A», RUT N°: 96.708.570-7, en su caso, la que "
       . "actuará en nombre y en representación e interés de la Universidad Miguel de Cervantes en las gestiones de "
       . "cobranza extrajudicial. Lo anterior es sin perjuicio de que la empresa señalada puede cambiar por decisión "
       . "unilateral de la UMC. Esta  cobranza extrajudicial  será realizada conforme a la ley, en días hábiles y en "
       . "horario de 09.00 a 20.00 horas.<br><br>"
       . "El alumno y su apoderado por este instrumento, declaran conocer y aceptar que, de acuerdo a lo establecido en "
       . "la ley Nº 19.628 sobre Protección de Datos de Carácter Personal, y para que la empresa «Servicios de Control "
       . "de Crédito S.A» pueda realizar la respectiva cobranza extrajudicial y /o judicial, la Universidad Miguel de "
       . "Cervantes suministrará a dicha empresa antecedentes, tanto respecto de los créditos morosos de sus deudores y "
       . "otros que no estando en dicha condición estén asociados a éstos, como de los antecedentes comerciales de los "
       . "deudores, tales como nombres y apellidos, cédula nacional de identidad, rol único tributario, domicilios, "
       . "direcciones y teléfonos, etc.<br><br>"
       . "Las tarifas de honorarios por concepto de la cobranza extrajudicial, y en conformidad a la ley de protección "
       . "del consumidor, ascenderán a los porcentajes aplicados sobre el total de la deuda o la cuota vencida, según "
       . "el caso, conforme a la siguiente escala progresiva: a) Obligaciones hasta 10 Unidades de Fomento  9%, b) por "
       . "la parte que exceda de 10 UF y hasta 50 UF 6% y c) por la parte que exceda de 50 UF  3%. El plazo para la "
       . "aplicación de honorarios será de 15 días corridos de atraso (mora) desde el día de vencimiento de la "
       . "obligación.<br><br>"
       . "Los gastos judiciales corresponderán a las costas procesales y honorarios profesionales del abogado o "
       . "empresa de cobranza externa a quien se le encargue dicha <br><br>"
       . "El alumno y su apoderado compareciente, declaran su conocimiento y conformidad con lo establecido en los "
       . "párrafos anteriores de esta cláusula.<br><br>"
       . "<b>DUODÉCIMO</b><br>"
       . "El estudiante y su apoderado declaran haber leído detalladamente el presente contrato y estar de acuerdo "
       . "con todas y cada una de sus estipulaciones, y toman debida nota de que el contenido de este documento es "
       . "el único que regula la relación contractual entre la UMC y el estudiante y su apoderado.<br>"
       . "La vigencia del presente contrato es exclusivamente por el período académico señalado en este instrumento. "
       . "La celebración de un nuevo contrato entre las partes está condicionada al estricto cumplimiento por parte "
       . "del estudiante de lo establecido en los Reglamentos que regulan sus estudios.<br><br>"
       . "La solicitud para renovar la prestación de los servicios educacionales por un nuevo periodo académico, "
       . "deberá ser realizada oportunamente, dentro de los plazos establecidos por la UMC.<br><br>"
       . "El presente contrato es firmado por parte de la Universidad bajo el supuesto que todo lo declarado por "
       . "el Estudiante y su apoderado, así como la documentación requerida y proporcionada, son fidedignos. En "
       . "el evento que ello no fuere efectivo, el presente contrato terminará de pleno derecho, no correspondiendo "
       . "a la Universidad efectuar devolución alguna de las sumas ya pagadas o documentadas de la matrícula, el "
       . "arancel, o cualquiera de las sumas o cuotas pactadas.<br><br>"
       . "<!-- PAGE BREAK -->"
       . "Para todos los efectos legales derivados del "
       . "presente contrato, las partes fijan domicilio en la ciudad de Santiago y se someten a la jurisdicción "
       . "de los tribunales de justicia. El presente contrato se firma en tres ejemplares del mismo tenor, "
       . "quedando uno en poder del alumno(a), y dos en poder de la UMC.<br><br>"
       . "<br><br><br><br><br><br>"
       . "<table align='center'>"
       . "  <tr><td><hr size='1' noshade>p.p. Universidad Miguel de Cervantes</td></tr>"
       . "</table><br><br><br><br><br><br>"
       . "<table align='center'>"
       . "  <tr>"
       . "    <td width='150' align='center'><hr size='1' noshade>Apoderado</td>"
       . "    <td width='100'>&nbsp;</td>"
       . "    <td width='150' align='center'><hr size='1' noshade>Alumno</td>"
       . "  </tr>"
       . "</table><br><br>"
       . "En Santiago de Chile, a $fecha_contrato";

$HTML = "<html>".$LF
      . "  <head>".$LF
      . "    <title>UMC - SGU - Contrato de Servicios Educacionales</title>".$LF
      . "    <style>".$LF
      . "      td { font-size: 12px; font-family: sans,arial,helvetica; }".$LF
      . "      @media print {".$LF
      . "        @page {page-break-after: always; size: 21.5cm 25cm; }".$LF
      . "        td { font-size: 12px; font-family: sans,arial,helvetica; }".$LF
      . "      }".$LF
      . "    </style>".$LF
      . "  </head>".$LF
      . "  <body background='$imagen_fondo'>".$LF
      . "    <table width='100%'>".$LF
      . "      <tr>".$LF
      . "        <td>".$LF
      . "          <table width='100%'><tr><td align='center'>$titulo</td>/tr></table><br>".$LF
      . "          <table>".$LF
      . "            <tr><td valign='top' align='justify'>$TEXTO</td></tr>".$LF
      . "          </table>".$LF
      . "        </td>".$LF
      . "      </tr>".$LF
      . "    </table>".$LF
      . "  </body>".$LF
      . "</html>".$LF;

?>
