COPY (SELECT to_char(c.fecha,'DD-MM-YYYY') as fecha_emision,
                            (SELECT to_char(max(fecha_venc),'DD-MM-YYYY') FROM finanzas.cobros where id_contrato=c.id) as fecha_venc,
                            '' as cta_ctble,
                            coalesce(c.arancel_efectivo,0)+coalesce(c.arancel_pagare_coleg,0)+coalesce(c.arancel_cheque,0)+coalesce(c.arancel_tarjeta_credito,0) as monto,
                            coalesce(va.rut,vp.rut) as rut,coalesce(va.nombre,vp.nombre) as razon_social,
                            c.id as nro_contrato,pc.id as nro_pagare 
                     FROM finanzas.contratos AS c 
                     LEFT JOIN vista_contratos AS vc USING (id)
                     LEFT JOIN vista_alumnos AS va ON va.id=c.id_alumno 
                     LEFT JOIN vista_pap     AS vp ON vp.id=c.id_pap 
                     LEFT JOIN finanzas.pagares_colegiatura AS pc ON pc.id_contrato=c.id
                     LEFT JOIN carreras        AS car ON car.id=c.id_carrera
                     WHERE (lower(pap.nombres||' '||pap.apellidos) ~* '' OR  pap.rut ~* '' OR lower(a.nombres||' '||a.apellidos) ~* '' OR  a.rut ~* '' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '' OR  av.rf_rut ~* '' OR  text(c.id) ~* '' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'cr[ií]st[ií]n[aá]' OR  pap.rut ~* 'cr[ií]st[ií]n[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'cr[ií]st[ií]n[aá]' OR  a.rut ~* 'cr[ií]st[ií]n[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'cr[ií]st[ií]n[aá]' OR  av.rf_rut ~* 'cr[ií]st[ií]n[aá]' OR  text(c.id) ~* 'cr[ií]st[ií]n[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'r[oó]m[aá]nn[eé]' OR  pap.rut ~* 'r[oó]m[aá]nn[eé]' OR lower(a.nombres||' '||a.apellidos) ~* 'r[oó]m[aá]nn[eé]' OR  a.rut ~* 'r[oó]m[aá]nn[eé]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'r[oó]m[aá]nn[eé]' OR  av.rf_rut ~* 'r[oó]m[aá]nn[eé]' OR  text(c.id) ~* 'r[oó]m[aá]nn[eé]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 's[eé]p[uú]lv[eé]d[aá]' OR  pap.rut ~* 's[eé]p[uú]lv[eé]d[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 's[eé]p[uú]lv[eé]d[aá]' OR  a.rut ~* 's[eé]p[uú]lv[eé]d[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 's[eé]p[uú]lv[eé]d[aá]' OR  av.rf_rut ~* 's[eé]p[uú]lv[eé]d[aá]' OR  text(c.id) ~* 's[eé]p[uú]lv[eé]d[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'f[ií]g[uú][eé]r[oó][aá]' OR  pap.rut ~* 'f[ií]g[uú][eé]r[oó][aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'f[ií]g[uú][eé]r[oó][aá]' OR  a.rut ~* 'f[ií]g[uú][eé]r[oó][aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'f[ií]g[uú][eé]r[oó][aá]' OR  av.rf_rut ~* 'f[ií]g[uú][eé]r[oó][aá]' OR  text(c.id) ~* 'f[ií]g[uú][eé]r[oó][aá]' ) 
                     ORDER BY c.fecha DESC ) to stdout WITH CSV HEADER