COPY (SELECT to_char(c.fecha,'DD-MM-YYYY') as fecha_emision,
                            (SELECT to_char(max(fecha_venc),'DD-MM-YYYY') FROM finanzas.cobros where id_contrato=c.id) as fecha_venc,
                            '' as cta_ctble,
                            coalesce(c.arancel_efectivo,0)+coalesce(c.arancel_pagare_coleg,0)+coalesce(c.arancel_cheque,0)+coalesce(c.arancel_tarjeta_credito,0) as monto,
                            coalesce(va.rut,vp.rut) as rut,coalesce(va.nombre,vp.nombre) as razon_social,
                            c.id as nro_contrato,pc.id as nro_pagare 
                     FROM finanzas.contratos AS c 
                     LEFT JOIN vista_contratos AS vc USING (id)
                     LEFT JOIN vista_alumnos AS va ON va.id=c.id_alumno 
                     LEFT JOIN vista_pap     AS vp ON vp.id=c.id_pap 
                     LEFT JOIN finanzas.pagares_colegiatura AS pc ON pc.id_contrato=c.id
                     LEFT JOIN carreras        AS car ON car.id=c.id_carrera
                     WHERE (lower(pap.nombres||' '||pap.apellidos) ~* 'g[oó]nz[aá]l[eé]z' OR  pap.rut ~* 'g[oó]nz[aá]l[eé]z' OR lower(a.nombres||' '||a.apellidos) ~* 'g[oó]nz[aá]l[eé]z' OR  a.rut ~* 'g[oó]nz[aá]l[eé]z' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'g[oó]nz[aá]l[eé]z' OR  av.rf_rut ~* 'g[oó]nz[aá]l[eé]z' OR  text(c.id) ~* 'g[oó]nz[aá]l[eé]z' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[oó]sc[oó]s[oó]' OR  pap.rut ~* 'm[oó]sc[oó]s[oó]' OR lower(a.nombres||' '||a.apellidos) ~* 'm[oó]sc[oó]s[oó]' OR  a.rut ~* 'm[oó]sc[oó]s[oó]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[oó]sc[oó]s[oó]' OR  av.rf_rut ~* 'm[oó]sc[oó]s[oó]' OR  text(c.id) ~* 'm[oó]sc[oó]s[oó]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[aá]t[ií][aá]s' OR  pap.rut ~* 'm[aá]t[ií][aá]s' OR lower(a.nombres||' '||a.apellidos) ~* 'm[aá]t[ií][aá]s' OR  a.rut ~* 'm[aá]t[ií][aá]s' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[aá]t[ií][aá]s' OR  av.rf_rut ~* 'm[aá]t[ií][aá]s' OR  text(c.id) ~* 'm[aá]t[ií][aá]s' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '[aá]d[oó]n[ií]s' OR  pap.rut ~* '[aá]d[oó]n[ií]s' OR lower(a.nombres||' '||a.apellidos) ~* '[aá]d[oó]n[ií]s' OR  a.rut ~* '[aá]d[oó]n[ií]s' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[aá]d[oó]n[ií]s' OR  av.rf_rut ~* '[aá]d[oó]n[ií]s' OR  text(c.id) ~* '[aá]d[oó]n[ií]s' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'd[uú]b[aá]n' OR  pap.rut ~* 'd[uú]b[aá]n' OR lower(a.nombres||' '||a.apellidos) ~* 'd[uú]b[aá]n' OR  a.rut ~* 'd[uú]b[aá]n' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'd[uú]b[aá]n' OR  av.rf_rut ~* 'd[uú]b[aá]n' OR  text(c.id) ~* 'd[uú]b[aá]n' ) 
                     ORDER BY c.fecha DESC ) to stdout WITH CSV HEADER