COPY (SELECT to_char(c.fecha,'DD-MM-YYYY') as fecha_emision,
                            (SELECT to_char(max(fecha_venc),'DD-MM-YYYY') FROM finanzas.cobros where id_contrato=c.id) as fecha_venc,
                            '' as cta_ctble,
                            coalesce(c.arancel_efectivo,0)+coalesce(c.arancel_pagare_coleg,0)+coalesce(c.arancel_cheque,0)+coalesce(c.arancel_tarjeta_credito,0) as monto,
                            coalesce(va.rut,vp.rut) as rut,coalesce(va.nombre,vp.nombre) as razon_social,
                            c.id as nro_contrato,pc.id as nro_pagare 
                     FROM finanzas.contratos AS c 
                     LEFT JOIN vista_contratos AS vc USING (id)
                     LEFT JOIN vista_alumnos AS va ON va.id=c.id_alumno 
                     LEFT JOIN vista_pap     AS vp ON vp.id=c.id_pap 
                     LEFT JOIN finanzas.pagares_colegiatura AS pc ON pc.id_contrato=c.id
                     LEFT JOIN carreras        AS car ON car.id=c.id_carrera
                     WHERE (lower(pap.nombres||' '||pap.apellidos) ~* '' OR  pap.rut ~* '' OR lower(a.nombres||' '||a.apellidos) ~* '' OR  a.rut ~* '' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '' OR  av.rf_rut ~* '' OR  text(c.id) ~* '' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'j[eé]ss[ií]c[aá]' OR  pap.rut ~* 'j[eé]ss[ií]c[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'j[eé]ss[ií]c[aá]' OR  a.rut ~* 'j[eé]ss[ií]c[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'j[eé]ss[ií]c[aá]' OR  av.rf_rut ~* 'j[eé]ss[ií]c[aá]' OR  text(c.id) ~* 'j[eé]ss[ií]c[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '[aá]ndr[eé][aá]' OR  pap.rut ~* '[aá]ndr[eé][aá]' OR lower(a.nombres||' '||a.apellidos) ~* '[aá]ndr[eé][aá]' OR  a.rut ~* '[aá]ndr[eé][aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[aá]ndr[eé][aá]' OR  av.rf_rut ~* '[aá]ndr[eé][aá]' OR  text(c.id) ~* '[aá]ndr[eé][aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '[aá]r[aá]v[eé]n[aá]' OR  pap.rut ~* '[aá]r[aá]v[eé]n[aá]' OR lower(a.nombres||' '||a.apellidos) ~* '[aá]r[aá]v[eé]n[aá]' OR  a.rut ~* '[aá]r[aá]v[eé]n[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[aá]r[aá]v[eé]n[aá]' OR  av.rf_rut ~* '[aá]r[aá]v[eé]n[aá]' OR  text(c.id) ~* '[aá]r[aá]v[eé]n[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 's[aá]nh[uú][eé]z[aá]' OR  pap.rut ~* 's[aá]nh[uú][eé]z[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 's[aá]nh[uú][eé]z[aá]' OR  a.rut ~* 's[aá]nh[uú][eé]z[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 's[aá]nh[uú][eé]z[aá]' OR  av.rf_rut ~* 's[aá]nh[uú][eé]z[aá]' OR  text(c.id) ~* 's[aá]nh[uú][eé]z[aá]' ) 
                     ORDER BY c.fecha DESC ) to stdout WITH CSV HEADER