COPY (SELECT to_char(c.fecha,'DD-MM-YYYY') as fecha_emision,
                            (SELECT to_char(max(fecha_venc),'DD-MM-YYYY') FROM finanzas.cobros where id_contrato=c.id) as fecha_venc,
                            '' as cta_ctble,
                            coalesce(c.arancel_efectivo,0)+coalesce(c.arancel_pagare_coleg,0)+coalesce(c.arancel_cheque,0)+coalesce(c.arancel_tarjeta_credito,0) as monto,
                            coalesce(va.rut,vp.rut) as rut,coalesce(va.nombre,vp.nombre) as razon_social,
                            c.id as nro_contrato,pc.id as nro_pagare 
                     FROM finanzas.contratos AS c 
                     LEFT JOIN vista_contratos AS vc USING (id)
                     LEFT JOIN vista_alumnos AS va ON va.id=c.id_alumno 
                     LEFT JOIN vista_pap     AS vp ON vp.id=c.id_pap 
                     LEFT JOIN finanzas.pagares_colegiatura AS pc ON pc.id_contrato=c.id
                     LEFT JOIN carreras        AS car ON car.id=c.id_carrera
                     WHERE (lower(pap.nombres||' '||pap.apellidos) ~* 'r[oó]j[aá]s' OR  pap.rut ~* 'r[oó]j[aá]s' OR lower(a.nombres||' '||a.apellidos) ~* 'r[oó]j[aá]s' OR  a.rut ~* 'r[oó]j[aá]s' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'r[oó]j[aá]s' OR  av.rf_rut ~* 'r[oó]j[aá]s' OR  text(c.id) ~* 'r[oó]j[aá]s' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[aá][uú]r[eé][ií]r[aá]' OR  pap.rut ~* 'm[aá][uú]r[eé][ií]r[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'm[aá][uú]r[eé][ií]r[aá]' OR  a.rut ~* 'm[aá][uú]r[eé][ií]r[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[aá][uú]r[eé][ií]r[aá]' OR  av.rf_rut ~* 'm[aá][uú]r[eé][ií]r[aá]' OR  text(c.id) ~* 'm[aá][uú]r[eé][ií]r[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'g[eé]n[eé]s[ií]s' OR  pap.rut ~* 'g[eé]n[eé]s[ií]s' OR lower(a.nombres||' '||a.apellidos) ~* 'g[eé]n[eé]s[ií]s' OR  a.rut ~* 'g[eé]n[eé]s[ií]s' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'g[eé]n[eé]s[ií]s' OR  av.rf_rut ~* 'g[eé]n[eé]s[ií]s' OR  text(c.id) ~* 'g[eé]n[eé]s[ií]s' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'z[aá]h[aá]m[ií]r[aá]' OR  pap.rut ~* 'z[aá]h[aá]m[ií]r[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'z[aá]h[aá]m[ií]r[aá]' OR  a.rut ~* 'z[aá]h[aá]m[ií]r[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'z[aá]h[aá]m[ií]r[aá]' OR  av.rf_rut ~* 'z[aá]h[aá]m[ií]r[aá]' OR  text(c.id) ~* 'z[aá]h[aá]m[ií]r[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '' OR  pap.rut ~* '' OR lower(a.nombres||' '||a.apellidos) ~* '' OR  a.rut ~* '' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '' OR  av.rf_rut ~* '' OR  text(c.id) ~* '' ) 
                     ORDER BY c.fecha DESC ) to stdout WITH CSV HEADER