COPY (SELECT to_char(c.fecha,'DD-MM-YYYY') as fecha_emision,
                            (SELECT to_char(max(fecha_venc),'DD-MM-YYYY') FROM finanzas.cobros where id_contrato=c.id) as fecha_venc,
                            '' as cta_ctble,
                            coalesce(c.arancel_efectivo,0)+coalesce(c.arancel_pagare_coleg,0)+coalesce(c.arancel_cheque,0)+coalesce(c.arancel_tarjeta_credito,0) as monto,
                            coalesce(va.rut,vp.rut) as rut,coalesce(va.nombre,vp.nombre) as razon_social,
                            c.id as nro_contrato,pc.id as nro_pagare 
                     FROM finanzas.contratos AS c 
                     LEFT JOIN vista_contratos AS vc USING (id)
                     LEFT JOIN vista_alumnos AS va ON va.id=c.id_alumno 
                     LEFT JOIN vista_pap     AS vp ON vp.id=c.id_pap 
                     LEFT JOIN finanzas.pagares_colegiatura AS pc ON pc.id_contrato=c.id
                     LEFT JOIN carreras        AS car ON car.id=c.id_carrera
                     WHERE (lower(pap.nombres||' '||pap.apellidos) ~* '[ií]nf[aá]nt[eé]' OR  pap.rut ~* '[ií]nf[aá]nt[eé]' OR lower(a.nombres||' '||a.apellidos) ~* '[ií]nf[aá]nt[eé]' OR  a.rut ~* '[ií]nf[aá]nt[eé]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[ií]nf[aá]nt[eé]' OR  av.rf_rut ~* '[ií]nf[aá]nt[eé]' OR  text(c.id) ~* '[ií]nf[aá]nt[eé]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[eé]d[ií]n[aá]' OR  pap.rut ~* 'm[eé]d[ií]n[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'm[eé]d[ií]n[aá]' OR  a.rut ~* 'm[eé]d[ií]n[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[eé]d[ií]n[aá]' OR  av.rf_rut ~* 'm[eé]d[ií]n[aá]' OR  text(c.id) ~* 'm[eé]d[ií]n[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[aá]rc[eé]l[oó]' OR  pap.rut ~* 'm[aá]rc[eé]l[oó]' OR lower(a.nombres||' '||a.apellidos) ~* 'm[aá]rc[eé]l[oó]' OR  a.rut ~* 'm[aá]rc[eé]l[oó]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[aá]rc[eé]l[oó]' OR  av.rf_rut ~* 'm[aá]rc[eé]l[oó]' OR  text(c.id) ~* 'm[aá]rc[eé]l[oó]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '[eé]r[ií]c' OR  pap.rut ~* '[eé]r[ií]c' OR lower(a.nombres||' '||a.apellidos) ~* '[eé]r[ií]c' OR  a.rut ~* '[eé]r[ií]c' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[eé]r[ií]c' OR  av.rf_rut ~* '[eé]r[ií]c' OR  text(c.id) ~* '[eé]r[ií]c' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'p[aá]tr[ií]c[ií][oó]' OR  pap.rut ~* 'p[aá]tr[ií]c[ií][oó]' OR lower(a.nombres||' '||a.apellidos) ~* 'p[aá]tr[ií]c[ií][oó]' OR  a.rut ~* 'p[aá]tr[ií]c[ií][oó]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'p[aá]tr[ií]c[ií][oó]' OR  av.rf_rut ~* 'p[aá]tr[ií]c[ií][oó]' OR  text(c.id) ~* 'p[aá]tr[ií]c[ií][oó]' ) 
                     ORDER BY c.fecha DESC ) to stdout WITH CSV HEADER