COPY (SELECT to_char(c.fecha,'DD-MM-YYYY') as fecha_emision,
                            (SELECT to_char(max(fecha_venc),'DD-MM-YYYY') FROM finanzas.cobros where id_contrato=c.id) as fecha_venc,
                            '' as cta_ctble,
                            coalesce(c.arancel_efectivo,0)+coalesce(c.arancel_pagare_coleg,0)+coalesce(c.arancel_cheque,0)+coalesce(c.arancel_tarjeta_credito,0) as monto,
                            coalesce(va.rut,vp.rut) as rut,coalesce(va.nombre,vp.nombre) as razon_social,
                            c.id as nro_contrato,pc.id as nro_pagare 
                     FROM finanzas.contratos AS c 
                     LEFT JOIN vista_contratos AS vc USING (id)
                     LEFT JOIN vista_alumnos AS va ON va.id=c.id_alumno 
                     LEFT JOIN vista_pap     AS vp ON vp.id=c.id_pap 
                     LEFT JOIN finanzas.pagares_colegiatura AS pc ON pc.id_contrato=c.id
                     LEFT JOIN carreras        AS car ON car.id=c.id_carrera
                     WHERE (lower(pap.nombres||' '||pap.apellidos) ~* '' OR  pap.rut ~* '' OR lower(a.nombres||' '||a.apellidos) ~* '' OR  a.rut ~* '' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '' OR  av.rf_rut ~* '' OR  text(c.id) ~* '' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[aá]r[ií][aá]n[eé]l[aá]' OR  pap.rut ~* 'm[aá]r[ií][aá]n[eé]l[aá]' OR lower(a.nombres||' '||a.apellidos) ~* 'm[aá]r[ií][aá]n[eé]l[aá]' OR  a.rut ~* 'm[aá]r[ií][aá]n[eé]l[aá]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[aá]r[ií][aá]n[eé]l[aá]' OR  av.rf_rut ~* 'm[aá]r[ií][aá]n[eé]l[aá]' OR  text(c.id) ~* 'm[aá]r[ií][aá]n[eé]l[aá]' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '[eé]l[ií]z[aá]b[eé]th' OR  pap.rut ~* '[eé]l[ií]z[aá]b[eé]th' OR lower(a.nombres||' '||a.apellidos) ~* '[eé]l[ií]z[aá]b[eé]th' OR  a.rut ~* '[eé]l[ií]z[aá]b[eé]th' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[eé]l[ií]z[aá]b[eé]th' OR  av.rf_rut ~* '[eé]l[ií]z[aá]b[eé]th' OR  text(c.id) ~* '[eé]l[ií]z[aá]b[eé]th' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* '[aá]r[ií][aá]s' OR  pap.rut ~* '[aá]r[ií][aá]s' OR lower(a.nombres||' '||a.apellidos) ~* '[aá]r[ií][aá]s' OR  a.rut ~* '[aá]r[ií][aá]s' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* '[aá]r[ií][aá]s' OR  av.rf_rut ~* '[aá]r[ií][aá]s' OR  text(c.id) ~* '[aá]r[ií][aá]s' ) AND (lower(pap.nombres||' '||pap.apellidos) ~* 'm[aá]nd[oó]l[ií]n[ií]' OR  pap.rut ~* 'm[aá]nd[oó]l[ií]n[ií]' OR lower(a.nombres||' '||a.apellidos) ~* 'm[aá]nd[oó]l[ií]n[ií]' OR  a.rut ~* 'm[aá]nd[oó]l[ií]n[ií]' OR lower(av.rf_nombres||' '||av.rf_apellidos) ~* 'm[aá]nd[oó]l[ií]n[ií]' OR  av.rf_rut ~* 'm[aá]nd[oó]l[ií]n[ií]' OR  text(c.id) ~* 'm[aá]nd[oó]l[ií]n[ií]' ) 
                     ORDER BY c.fecha DESC ) to stdout WITH CSV HEADER