COPY (SELECT c.id,cod_asignatura||'-'||c.seccion||' '||asignatura AS asignatura,profesor,rut,
                           u.funcion||coalesce(' ('||horas_planta_docencia||')','') as funcion,
                           u.categorizacion,cant_alumnos_asist(c.id),ga.nombre AS grado_academico,
                           2022-(SELECT min(ano) FROM cursos WHERE id_profesor=u.id)+1 AS antiguedad,
                           (SELECT count(id) AS cant_sesiones FROM cursos_sesiones WHERE id_curso=c.id) AS cant_sesiones,
                           c.semestre||'-'||c.ano AS periodo,sesion1,sesion2,sesion3,(SELECT CASE WHEN count(id)=count(materia) AND count(id)>0 THEN 'SI' WHEN c.seccion=9 THEN 'NC' ELSE 'NO' END AS cal FROM calendarizaciones WHERE id_curso=c.id) AS calendarizado,
                           to_char(c.fec_ini,'TMDay DD-tmMon-YYYY') AS fec_ini,to_char(c.fec_fin,'TMDay DD-tmMon-YYYY') AS fec_fin,c.seccion,
                           (SELECT char_comma_sum(vc.cod_asignatura||'-'||vc.seccion||' '||vc.asignatura) AS asig_fusionadas FROM vista_gestion_cursos AS vc LEFT JOIN cursos AS ca USING (id) WHERE ca.id_fusion = c.id) AS asig_fusionadas,
                           CASE WHEN ayudantia THEN 'Si' ELSE 'No' END AS ayudantia
                    FROM vista_gestion_cursos AS vc
                    LEFT JOIN cursos AS c USING (id)
                    LEFT JOIN carreras AS car ON car.id=vc.id_carrera
                    LEFT JOIN usuarios AS u ON u.id=vc.id_profesor
                    LEFT JOIN grado_acad AS ga ON ga.id=u.grado_academico
                    WHERE id_fusion IS NULL  AND (lower(asignatura) ~* 'd[ií]pl[oó]m[aá]d[oó]' OR       cod_asignatura ~* 'd[ií]pl[oó]m[aá]d[oó]' OR       text(c.id) ~* 'd[ií]pl[oó]m[aá]d[oó]' OR       lower(profesor) ~* 'd[ií]pl[oó]m[aá]d[oó]')  AND (lower(asignatura) ~* '[eé]n' OR       cod_asignatura ~* '[eé]n' OR       text(c.id) ~* '[eé]n' OR       lower(profesor) ~* '[eé]n')  AND (lower(asignatura) ~* 'g[eé]st[ií][oó]n' OR       cod_asignatura ~* 'g[eé]st[ií][oó]n' OR       text(c.id) ~* 'g[eé]st[ií][oó]n' OR       lower(profesor) ~* 'g[eé]st[ií][oó]n')  AND (lower(asignatura) ~* 'pr[eé]s[uú]p[uú][eé]st[aá]r[ií][aá]' OR       cod_asignatura ~* 'pr[eé]s[uú]p[uú][eé]st[aá]r[ií][aá]' OR       text(c.id) ~* 'pr[eé]s[uú]p[uú][eé]st[aá]r[ií][aá]' OR       lower(profesor) ~* 'pr[eé]s[uú]p[uú][eé]st[aá]r[ií][aá]')  AND (lower(asignatura) ~* 'y' OR       cod_asignatura ~* 'y' OR       text(c.id) ~* 'y' OR       lower(profesor) ~* 'y')  AND (lower(asignatura) ~* 'f[ií]n[aá]nc[ií][eé]r[aá]' OR       cod_asignatura ~* 'f[ií]n[aá]nc[ií][eé]r[aá]' OR       text(c.id) ~* 'f[ií]n[aá]nc[ií][eé]r[aá]' OR       lower(profesor) ~* 'f[ií]n[aá]nc[ií][eé]r[aá]')  AND (lower(asignatura) ~* 'p[aá]r[aá]' OR       cod_asignatura ~* 'p[aá]r[aá]' OR       text(c.id) ~* 'p[aá]r[aá]' OR       lower(profesor) ~* 'p[aá]r[aá]')  AND (lower(asignatura) ~* '[ií]nst[ií]t[uú]c[ií][oó]n[eé]s' OR       cod_asignatura ~* '[ií]nst[ií]t[uú]c[ií][oó]n[eé]s' OR       text(c.id) ~* '[ií]nst[ií]t[uú]c[ií][oó]n[eé]s' OR       lower(profesor) ~* '[ií]nst[ií]t[uú]c[ií][oó]n[eé]s')  AND (lower(asignatura) ~* 'm[uú]n[ií]c[ií]p[aá]l[eé]s' OR       cod_asignatura ~* 'm[uú]n[ií]c[ií]p[aá]l[eé]s' OR       text(c.id) ~* 'm[uú]n[ií]c[ií]p[aá]l[eé]s' OR       lower(profesor) ~* 'm[uú]n[ií]c[ií]p[aá]l[eé]s')  
                    ORDER BY c.ano DESC, c.semestre DESC, vc.carrera, c.seccion, cod_asignatura ) to stdout WITH CSV HEADER